#!/usr/bin/env python

import typing
import argparse
import subprocess


def run(command: typing.List[str]) -> str:
    completed = subprocess.run(
        ' '.join(map(str, command)), 
        encoding='UTF-8', 
        shell=True, 
        capture_output=True
    )
    completed.check_returncode()
    return completed.stdout


TEMPLATE = ['brightnessctl', r'--device="asus::kbd_backlight"']


if __name__ == '__main__':
    
    # Handle CLI
    parser = argparse.ArgumentParser()
    parser.add_argument('action', action='store')
    args = parser.parse_args()

    # Get current level and adjust it to 'action'
    current_level = int(run([*TEMPLATE, 'get']))
    max_level = int(run([*TEMPLATE, 'max']))

    if args.action.lower() == 'increase':
        current_level = min(current_level + 1, max_level)
    elif args.action.lower() == 'decrease':
        current_level = max(current_level - 1, 0)
    else:
        raise ValueError(f'expect decrease or increase, got {args.action} instead')
    
    run([*TEMPLATE, 'set', current_level])